# Calendar 领取任务
POST /task/receiveTask HTTP/1.1
Host: uoes-cneast-test-rx4-test05.test.paas-test.sheincorp.cn
User-Agent: Apifox/1.0.0 (https://apifox.com)
Content-Type: application/json
Accept: */*
Host: uoes-cneast-test-rx4-test05.test.paas-test.sheincorp.cn
Connection: keep-alive

{
  "activity_id": 2255,
  "activity_source_system": null,
  "activity_source_type": null,
  "anti_in": "",
  "app_version": "10.0.2",
  "blackbox": "",
  "brand_id": "7",
  "browser_mode": "",
  "currency": "USD",
  "device_no": "shein_1b780b07-93f0-341f-a235-ce7e22059aad",
  "device_system_version": "",
  "ftoken": "",
  "ip": "10.84.200.21",
  "language": "en",
  "member_id": 90000047435,
  "page_source": "",
  "site_uid": "iosshus",
  "sm_device_id": "202311061558122253a9920d5853353eb4552bc755a46300d85befe64ac296",
  "task_id": null,
  "task_ids":[],
  "user_task_end_time": null,
  "ext_content":""
}